
[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-tools/go-steputils"

[[constraint]]
  branch = "master"
  name = "github.com/kballard/go-shellquote"

[[constraint]]
  name = "github.com/bitrise-community/steps-ionic-archive"
  branch = "master"
